config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  
  resources :categories, except: [:destroy]
  resources :comments
  end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name, case_sensitive: false
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :require_admin, except: [:index, :show]
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
           flash[:success] = "Category name was successfully updated" 
           redirect_to categories_path(@category)
        else
            render 'edit'
        end
    end
    
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
    
    
    private
        def category_params
            params.require(:category).permit(:name)
        end
        
        def require_admin
            if !logged_in? || (logged_in? && !current_user.admin?)
                flash[:danger] = "Only admins can perform the action"
                redirect_to categories_path
            end
        end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
    <div class="content">
        <div class='row'>
           <div class='col-md-12'>
            <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
                <div class="form-group">
                    <div class="control-label col-sm-2">
                        <%= f.label :name %>
                    </div>
                    <div class="col-sm-8">
                        <%= f.text_field :name, class:"form-control", placeholder: "Category name", autofocus: true %>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <%= f.submit class:'btn btn-primary btn-lg btn-style' %>
                    </div>
                </div>
            <div class="col-xs-4 col-xs-offset-5">
                [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
            </div>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit categories</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Listing all categories</h1>
<div class="col-sm-2">
    <%= link_to "New Articles", new_article_path, class:"btn btn-primary btn-lg btn-style2" %>
</div>
<div class="col-sm-offset-2">
    <%= will_paginate %>
</div>
    <% @categories.each do |category| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-xs-5 col-xs-offset-4">
                    <li class="category-title">
                        <%= link_to "#{category.name}", category_path(category) %>
                    </li>
                    <li align="center"><small><%= pluralize(category.articles.count, "article") %></small></li>
                    <% if logged_in? && current_user.admin? %>
                        <div align="right">
                        <%= link_to "Edit Category Name", edit_category_path(category), class: "btn btn-xs btn-primary" %>
                    </div>
                    <% end %>
                </div>
            </div>
        </ul>
    <% end %>
<div class="col-sm-offset-2">
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1>Create new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div class="col-sm-3">
    <%= link_to "New Articles", new_article_path, class:"btn btn-primary btn-lg btn-style2" %>
</div>
<div class="col-sm-offset-2">
    <div class="paginate">
        <%= will_paginate @category_articles %>
    </div>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class="col-sm-offset-2">
    <div class="paginate">
        <%= will_paginate @category_articles %>
    </div>
</div>